= Contexto: el impulso de la democracia participativa en los ayuntamientos del cambio

Los resultados de las elecciones municipales celebradas en mayo de 2015 permitieron la configuración de gobiernos municipales liderados por partidos políticos constituidos en torno a plataformas ciudadanas vinculadas al 15M. Estos gobiernos municipales se han pensado en red; una red de "ciudades del cambio" o "`ciudades rebeldes`" que han establecido dinámicas de coordinación y colaboración inéditas hasta ahora, que orientan su municipalismo hacia la transformación también del estado, de la Unión Europea y de la gobernanza global.

Estos gobiernos del cambio nacen con la promesa no sólo de hacer cosas distintas, sino de hacerlas de forma distinta: recogiendo aquellas aspiraciones del 15M que lograron una simpatía de más del 70% de la población, y que se sintetizan en la demanda de "democracia real".

Una de los ejes de acción más claros para la regeneración democrática de los gobiernos locales es el impulso de los procesos participativos de la ciudadanía en la gobernanza municipal. Para ello se han iniciado desarrollos tecnológicos que posibiliten una participación amplia, y que lo hagan con una perspectiva tecnopolítica crítica, evitando así prácticas superficiales que no supongan un cambio sustancial en la gobernanza municipal.

En esta etapa aún breve del municipalismo del cambio, el Ayuntamiento de Madrid ha sido el que más ha avanzado en el desarrollo e implantación de tecnologías digitales para la participación. La principal herramienta que han desarrollado es "Consul - Citizen Participation and Open Government Application", cuyo código está disponible en GitHub con una licencia abierta. Las razones por la cual Consul se desarrolla como software libre han sido explicitadas en el site "`Decide Madrid`":

_Utilízalo en tu municipio libremente o ayúdanos a mejorarlo, es software libre.*_ Este Portal de Gobierno Abierto usa la aplicación Consul que es software libre, con licencia AGPLv3, esto significa en palabras sencillas, que cualquiera puede libremente usar el código, copiarlo, verlo en detalle, modificarlo, y redistribuirlo al mundo con las modificaciones que quiera (manteniendo el que otros puedan a su vez hacer lo mismo). Porque creemos que la cultura es mejor y más rica cuando se libera.&#x20;

Existe por tanto un potencial de trabajo en red para el desarrollo distribuido de Consul, de forma que las modificaciones (mejoras, nuevas funcionalidades, optimización del código, etc.) realizadas en cada municipio puedan ser aprovechadas no sólo por el Ayuntamiento de Madrid, si no por cualquier otro municipio. El impulso de la participación ciudadana está creciendo en numerosos ayuntamientos de todo corte político, que por su proximidad al ciudadano, son más sensibles a dar respuesta a sus inquietudes y demandas. Unos por convicción y otros por mímesis o supervivencia política, están planificando procesos de participación ciudadana, y experimentando y evaluando herramientas digitales (libres y propietarias) para facilitarlos. Un indicio de la probable explosión en el uso municipal de herramientas participativas digitales es el anuncio de Telefónica de invertir 80 millones en el desarrollo de las mismas.

En septiembre de 2015, Consul fue utilizada por primera vez en el sitio web "Decide Madrid", y posteriormente ha sido también puesta en marcha en sitios web similares en Barcelona, La Coruña y Oviedo. Otros ayuntamientos han mostrado también su interés por el uso de la herramienta y están considerando en estos momentos su adopción. A continuación se detallan los forks actualmente en producción:

|===
| Nombre del fork | Mantenedor | URL | URL Github | Comentario

| Consul
| Ayuntamiento de Madrid
| No aplica
| https://github.com/consul/consul
| El código original base para el resto de proyectos. No se encuentra disponible en ninguna URL publicable.

| Decide Madrid
| Ayuntamiento de Madrid
| https://decide.madrid.es/
| https://github.com/AyuntamientoMadrid/consul
| El código coincide con lo que hay en producción

| decidim.barcelona
| Ajuntament de Barcelona
| https://decidim.barcelona/
| https://github.com/AjuntamentdeBarcelona/decidim.barcelona
| El código coincide con lo que hay en producción.

| Plaza Podemos 2.0
| Podemos
| https://plaza.podemos.info/
| https://github.com/podemos-info/participacion
| El código coincide con lo que hay en producción en la rama de git de production.

| Ho Podem Tot
| Ho Podem Tot
| http://ara.hopodemtot.info/
| No aplica
| No han publicado el código

| Consulta Oviedo
| Ayuntamiento de Oviedo
| http://www.consultaoviedo.es/
| No aplica
| No han publicado el código

| A Porta Aberta
| Concello da Coruña
| https://aportaaberta.coruna.es
| https://github.com/ConcelloCoruna/aportaaberta
| El código publicado no coincide con lo que hay en producción.
|===
